// <auto-generated />
using System;
using Arena.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arena.Persistence.Migrations
{
    [DbContext(typeof(ArenaContext))]
    [Migration("20240514190356_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Arena.Domain.Arena", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("ID");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ROUND_COUNT");

                    b.HasKey("Guid");

                    b.ToTable("Arena", "ar");
                });
#pragma warning restore 612, 618
        }
    }
}
